spring:
  output:
    ansi:
      enabled: always
  r2dbc:
    url: r2dbc:mysql://127.0.0.1:3306/database
    username: user
    password: password
  liquibase:
    change-log: classpath*:/db/changelog/changelog-master.xml
logging:
  level:
    io.netty.resolver.dns.DnsServerAddressStreamProviders: off
